-- MySQL Script generated by MySQL Workbench
-- Wed Dec 20 12:22:03 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_uni
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_uni
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_uni` DEFAULT CHARACTER SET utf8 ;
USE `db_uni` ;

-- -----------------------------------------------------
-- Table `db_uni`.`book_library`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_uni`.`book_library` ;

CREATE TABLE IF NOT EXISTS `db_uni`.`book_library` (
  `idBook_Library` INT(11) NOT NULL,
  `Title` VARCHAR(45) NULL DEFAULT NULL,
  `Author` VARCHAR(45) NULL DEFAULT NULL,
  `Description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idBook_Library`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_uni`.`book_student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_uni`.`book_student` ;

CREATE TABLE IF NOT EXISTS `db_uni`.`book_student` (
  `ISBN` VARCHAR(45) NOT NULL,
  `Student_ID` VARCHAR(45) NULL DEFAULT NULL,
  `Borrow_date` DATE NULL DEFAULT NULL,
  `Retrieval_date` DATE NULL DEFAULT NULL,
  `Penalty` INT(11) NULL DEFAULT NULL,
  `ID_BOOK` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ISBN`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_uni`.`courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_uni`.`courses` ;

CREATE TABLE IF NOT EXISTS `db_uni`.`courses` (
  `idcourses` INT(11) NOT NULL,
  `course_description` VARCHAR(45) NOT NULL,
  `major` VARCHAR(45) NOT NULL,
  `no_credits` VARCHAR(45) NOT NULL,
  `prequisites` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcourses`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_uni`.`prequisites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_uni`.`prequisites` ;

CREATE TABLE IF NOT EXISTS `db_uni`.`prequisites` (
  `course_code` INT(11) NOT NULL,
  `prequisite_code` VARCHAR(45) NOT NULL,
  `ID_presuisite` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_presuisite`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_uni`.`professors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_uni`.`professors` ;

CREATE TABLE IF NOT EXISTS `db_uni`.`professors` (
  `idprofessors` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `professorscol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idprofessors`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_uni`.`professors_courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_uni`.`professors_courses` ;

CREATE TABLE IF NOT EXISTS `db_uni`.`professors_courses` (
  `idprofessors_courses` INT(11) NOT NULL,
  `course_id` VARCHAR(45) NULL DEFAULT NULL,
  `semester` VARCHAR(45) NULL DEFAULT NULL,
  `evaluation` VARCHAR(45) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_uni`.`students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_uni`.`students` ;

CREATE TABLE IF NOT EXISTS `db_uni`.`students` (
  `idstudents` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `major` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `to_be_payed` VARCHAR(45) NOT NULL,
  `payment_status` VARCHAR(45) NOT NULL,
  `studentscol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idstudents`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_uni`.`prequisites_has_courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_uni`.`prequisites_has_courses` ;

CREATE TABLE IF NOT EXISTS `db_uni`.`prequisites_has_courses` (
  `prequisites_ID_presuisite` VARCHAR(45) NOT NULL,
  `courses_idcourses` INT(11) NOT NULL,
  PRIMARY KEY (`prequisites_ID_presuisite`, `courses_idcourses`),
  INDEX `fk_prequisites_has_courses_courses1_idx` (`courses_idcourses` ASC),
  INDEX `fk_prequisites_has_courses_prequisites_idx` (`prequisites_ID_presuisite` ASC),
  CONSTRAINT `fk_prequisites_has_courses_prequisites`
    FOREIGN KEY (`prequisites_ID_presuisite`)
    REFERENCES `db_uni`.`prequisites` (`ID_presuisite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prequisites_has_courses_courses1`
    FOREIGN KEY (`courses_idcourses`)
    REFERENCES `db_uni`.`courses` (`idcourses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_uni`.`students_has_book_student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_uni`.`students_has_book_student` ;

CREATE TABLE IF NOT EXISTS `db_uni`.`students_has_book_student` (
  `students_idstudents` INT(11) NOT NULL,
  `book_student_ISBN` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`students_idstudents`, `book_student_ISBN`),
  INDEX `fk_students_has_book_student_book_student1_idx` (`book_student_ISBN` ASC),
  INDEX `fk_students_has_book_student_students1_idx` (`students_idstudents` ASC),
  CONSTRAINT `fk_students_has_book_student_students1`
    FOREIGN KEY (`students_idstudents`)
    REFERENCES `db_uni`.`students` (`idstudents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_has_book_student_book_student1`
    FOREIGN KEY (`book_student_ISBN`)
    REFERENCES `db_uni`.`book_student` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_uni`.`professors_has_courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_uni`.`professors_has_courses` ;

CREATE TABLE IF NOT EXISTS `db_uni`.`professors_has_courses` (
  `professors_idprofessors` INT(11) NOT NULL,
  `courses_idcourses` INT(11) NOT NULL,
  `semester` VARCHAR(45) NULL,
  `evaluation` VARCHAR(45) NULL,
  `professors_has_coursescol` VARCHAR(45) NULL,
  PRIMARY KEY (`professors_idprofessors`, `courses_idcourses`),
  INDEX `fk_professors_has_courses_courses1_idx` (`courses_idcourses` ASC),
  INDEX `fk_professors_has_courses_professors1_idx` (`professors_idprofessors` ASC),
  CONSTRAINT `fk_professors_has_courses_professors1`
    FOREIGN KEY (`professors_idprofessors`)
    REFERENCES `db_uni`.`professors` (`idprofessors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professors_has_courses_courses1`
    FOREIGN KEY (`courses_idcourses`)
    REFERENCES `db_uni`.`courses` (`idcourses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_uni`.`book_library_has_students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_uni`.`book_library_has_students` ;

CREATE TABLE IF NOT EXISTS `db_uni`.`book_library_has_students` (
  `book_library_idBook_Library` INT(11) NOT NULL,
  `students_idstudents` INT(11) NOT NULL,
  `borrow_date` VARCHAR(45) NULL,
  `retrieval_date` VARCHAR(45) NULL,
  `penalty` VARCHAR(45) NULL,
  `book_name` VARCHAR(45) NULL,
  `book_library_has_studentscol` VARCHAR(45) NULL,
  PRIMARY KEY (`book_library_idBook_Library`, `students_idstudents`),
  INDEX `fk_book_library_has_students_students1_idx` (`students_idstudents` ASC),
  INDEX `fk_book_library_has_students_book_library1_idx` (`book_library_idBook_Library` ASC),
  CONSTRAINT `fk_book_library_has_students_book_library1`
    FOREIGN KEY (`book_library_idBook_Library`)
    REFERENCES `db_uni`.`book_library` (`idBook_Library`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_book_library_has_students_students1`
    FOREIGN KEY (`students_idstudents`)
    REFERENCES `db_uni`.`students` (`idstudents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_uni`.`students_has_professors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_uni`.`students_has_professors` ;

CREATE TABLE IF NOT EXISTS `db_uni`.`students_has_professors` (
  `students_idstudents` INT(11) NOT NULL,
  `professors_idprofessors` INT(11) NOT NULL,
  PRIMARY KEY (`students_idstudents`, `professors_idprofessors`),
  INDEX `fk_students_has_professors_professors1_idx` (`professors_idprofessors` ASC),
  INDEX `fk_students_has_professors_students1_idx` (`students_idstudents` ASC),
  CONSTRAINT `fk_students_has_professors_students1`
    FOREIGN KEY (`students_idstudents`)
    REFERENCES `db_uni`.`students` (`idstudents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_has_professors_professors1`
    FOREIGN KEY (`professors_idprofessors`)
    REFERENCES `db_uni`.`professors` (`idprofessors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_uni`.`courses_has_courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_uni`.`courses_has_courses` ;

CREATE TABLE IF NOT EXISTS `db_uni`.`courses_has_courses` (
  `courses_idcourses` INT(11) NOT NULL,
  `courses_idcourses1` INT(11) NOT NULL,
  PRIMARY KEY (`courses_idcourses`, `courses_idcourses1`),
  INDEX `fk_courses_has_courses_courses2_idx` (`courses_idcourses1` ASC),
  INDEX `fk_courses_has_courses_courses1_idx` (`courses_idcourses` ASC),
  CONSTRAINT `fk_courses_has_courses_courses1`
    FOREIGN KEY (`courses_idcourses`)
    REFERENCES `db_uni`.`courses` (`idcourses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_courses_has_courses_courses2`
    FOREIGN KEY (`courses_idcourses1`)
    REFERENCES `db_uni`.`courses` (`idcourses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
